import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./local.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=3.0" />

      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
